### ISSUE TITLE
Chunk Load taking 34% of tick

### ISSUE THREAD

**Issue by nseveryns** [PryPurity/WorldBorder#10]
**Describe the bug**:
Crashing server

**Server Version**:
1.16

**Plugin Version**:
2.0.8

**Plugins**:
N/A

Problem code tagged below along with server timings;

https://github.com/PryPurity/WorldBorder/blob/master/src/main/java/com/wimbli/WorldBorder/WBListener.java#L47
https://timings.aikar.co/?id=272aae2b44cb4a909c43ce6c5a492360#plugins

**Comment by PryPurity** [comment]
Took a look into it, and version 2.0.9 should fix most of this.
