### ISSUE TITLE
Paper 1.16.1 Nether Trim Command Not Functioning

### ISSUE THREAD

**Issue by Weasel-Beans** [PryPurity/WorldBorder#11]
On my Paper 1.16.1 test server whenever I try to do a trim on the Nether or End it doesn't work. It instantly returns with a 'completed!' message without removing any chunks. When I try to do this on the Overworld however, it works as it should. This is after I reduce the border size, so it definitely has chunks that need to be trimmed.

```
> wb world_nether trim
[20:27:41 INFO]: World trimming task is ready for world "world_nether", attempting to process up to 5000 chunks per second (default 20). The map will be trimmed past 208 blocks beyond the border (default 208).
[20:27:41 INFO]: This process can take a very long time depending on the world's overall size. Also, depending on the chunk processing rate, players may experience lag for the duration.
[20:27:41 INFO]: You should now use wb trim confirm to start the process.
[20:27:41 INFO]: You can cancel at any time with wb trim cancel, or pause/unpause with wb trim pause.
> wb trim confirm
[20:27:52 INFO]: WorldBorder map trimming task for world "world_nether" started.
[20:27:52 INFO]: [WorldBorder] [Trim] 0 entire region(s) and 0 individual chunk(s) trimmed so far (100.0% done)
[20:27:52 INFO]: [WorldBorder] [Trim] task successfully completed!
[20:27:52 INFO]: [WorldBorder] [Trim] NOTICE: it is recommended that you restart your server after a Trim, to be on the safe side.
[20:27:52 INFO]: [WorldBorder] [Trim] This especially true with DynMap. You should also run a fullrender in DynMap for the trimmed world after restarting, so trimmed chunks are updated on the map.

```
Timings report:

https://timings.aikar.co/?id=352ef99ce65d4698a50a302771ebfeb0

**Comment by PryPurity** [comment]
Can you try doing a full render of the worlds with dynmap/use Amulet, to make sure the chunks are still there?

**Comment by PryPurity** [comment]
Also, please use the right format

**Comment by Weasel-Beans** [comment]
I know that the chunks are still there. I can change the border size and run the command, and nothing changes. If I trim then extend the borders, I see the same chunks as before, including builds. The world folder remains the exact same size as it was before, and as you can see in that command nothing actually happens when the trim function is run.

I'm not sure what you mean by right format, I described the bug and gave a timings report which shows details of the server version, plugins, and plugin versions. That's all the default format asks for here.

It's probably worth mentioning that this also happened on the old version of WorldBorder before you forked it.

**Comment by PryPurity** [comment]
![ThYXyUnWHZ](https://user-images.githubusercontent.com/9400821/88730717-61d66d00-d0fc-11ea-82f6-aa2ed6f74a26.gif)

**Comment by Weasel-Beans** [comment]
As I just said, all of that information is included in detail in my first post in this thread. Timings v2 includes the exact server version, a complete list of all plugins, the exact versions of all of those plugins, and much more. But alright I'll copy and paste it here if that's what you want.

**Describe the bug**:
> On my Paper 1.16.1 test server whenever I try to do a trim on the Nether or End it doesn't work. It instantly returns with a 'completed!' message without removing any chunks. When I try to do this on the Overworld however, it works as it should. This is after I reduce the border size, so it definitely has chunks that need to be trimmed.
> 
> ```
> > wb world_nether trim
> [20:27:41 INFO]: World trimming task is ready for world "world_nether", attempting to process up to 5000 chunks per second (default 20). The map will be trimmed past 208 blocks beyond the border (default 208).
> [20:27:41 INFO]: This process can take a very long time depending on the world's overall size. Also, depending on the chunk processing rate, players may experience lag for the duration.
> [20:27:41 INFO]: You should now use wb trim confirm to start the process.
> [20:27:41 INFO]: You can cancel at any time with wb trim cancel, or pause/unpause with wb trim pause.
> > wb trim confirm
> [20:27:52 INFO]: WorldBorder map trimming task for world "world_nether" started.
> [20:27:52 INFO]: [WorldBorder] [Trim] 0 entire region(s) and 0 individual chunk(s) trimmed so far (100.0% done)
> [20:27:52 INFO]: [WorldBorder] [Trim] task successfully completed!
> [20:27:52 INFO]: [WorldBorder] [Trim] NOTICE: it is recommended that you restart your server after a Trim, to be on the safe side.
> [20:27:52 INFO]: [WorldBorder] [Trim] This especially true with DynMap. You should also run a fullrender in DynMap for the trimmed world after restarting, so trimmed chunks are updated on the map.
> ```
> 
> Timings report:
> 
> https://timings.aikar.co/?id=352ef99ce65d4698a50a302771ebfeb0

**Server Version**:

Paper-117 (MC: 1.16.1)

**Plugin Version**:

WorldBorder (v2.0.9)

**Plugins**:

AutoMessage, Calculator*, CoreProtect, CrateReloaded, CustomJoinNotif*, DiscordSRV, DragonSlayer, dynmap*, EmotePlugin3*, Essentials, EssentialsGeoIP, EssentialsSpawn, FarmHand, FarmLimiter, GiveMeArms, GriefPrevention, GriefPreventionFlags, Harbor, Hat, HorseTpWithMe, IllegalStack, KeepItems*, LimitPillagers, Lottery, LuckPerms, Matrix, MobHeads, MobHunting, MOTD, NoBedExplosions, OpenInv, PlaceholderAPI, PlayerParticles, Playtimes*, ProtocolLib, PvPToggle, QuickShop, RFChairs, SAML, Serverlist*, TabList, TradePlus, TreeGravity, Vault, VentureChat, VillagerOptimiser, Votifier, VotingPlugin, WorldBorder, WorldEdit, XProtect*

I don't understand why the issue was closed right after being opened though, as this was not solved in any way.
