### ISSUE TITLE
Fill runs in a Segmentation Violation

### ISSUE THREAD

**Issue by Bloodrayne1995** [PryPurity/WorldBorder#13]
**Describe the bug**:
At a certain point of the fill procedure, the Java VM crashes with a SIGSEGV - error.
We figure WorldBorder does raise this bug. If no fill or trim command is used, the server runs normally.
I dont think that you can do something against it, because the OS crashes the VM but maybe you got an idea
for that.

**Server Version**:
Paper 1.16.1 (build 136)

**Plugin Version**:
2.0.9

**Plugins**:
AFKnotify, AreaShop, AsyncWorldEdit, BungeeTabListPlus, ChatMentions*, Citizens, Clans, CMI, CMIPaperLib, CoreProtect, CraftBook, dynmap*, FunnyXT, HeadDatabase*, HolographicDisplays, LuckPerms, Multiverse-Core, NoChat*, ProtocolLib, Quests, ServerSigns, SimpleVoteListener*, Stargate, Towny, Vault, Votifier, WorldBorder, WorldEdit, WorldGuard

**Logfiles**
- Screenshot: [https://cloud.eona-minecraft.de/index.php/s/CbZ5gPdTTXtffkN](https://cloud.eona-minecraft.de/index.php/s/CbZ5gPdTTXtffkN)
- LogFiles: [https://hastebin.com/qemuzefibu.rb](https://hastebin.com/qemuzefibu.rb)    / [https://hastebin.com/ocebozibey.rb](https://hastebin.com/ocebozibey.rb)

Greetings
Bloodrayne

**Comment by PryPurity** [comment]
I'm not seeing anything in the logfiles that associate with Worldborder. It looks more as a OS problem, as you stated, than a Worldborder bug. 

Also, you can attach screenshots right here on github. :)

**Comment by Bloodrayne1995** [comment]
My reason for "blaming" worldborder is, that only if worldborder works something (fill / trim) this crash comes up.
I`m testing on a separate server without any plugins than WorldBorder and its dependencies at afternoon.

The fact, that the OS kills the JVM is my biggest question mark. All other exceptions are raised within the JVM.

**Comment by Bloodrayne1995** [comment]
I tested the same command on a separate server with only Wordborder installed. This MC-server runs on same host machine as the MC-Server which produce this error.

On the test server it runs smoothly. No JVM crashes.
I think that some other world using plugins (Dynmap, Multiverse) are causing this trouble and not Worldborder.

This issue can be closed in my opinion.

Greetings
Bloodrayne
