### ISSUE TITLE
Knockback does not work when there is a block occupying the knockback destination's X/Z-coordinate at the same Y level

### ISSUE THREAD

**Issue by Sabinno** [PryPurity/WorldBorder#17]
**Describe the bug**: When WorldBorder cannot find a suitable block for a player to be knocked back to that retains the same Y coordinate, the plugin just gives up and teleports the player in the spawn chunk. Ideally, this should be fixed by teleporting the player to free space with the closest Y coordinate. If none is available, just keep checking the next X/Z coordinate until a suitable space is found.

Reproduce this by creating a worldborder, then crossing it while stepping down from a block at the exact same time.

**Server Version**: paper-184

**Plugin Version**: 2.0.9

**Plugins**: CoordinatesObfuscator*, dynmap*, ProtocolLib, ProtocolPlugin, TCPShield*, VariableTime*, ViaVersion, WorldBorder

**Comment by PryPurity** [comment]
Please test out the newest version, 2.1.0!
