### ISSUE TITLE
World Border won't resume fill job after restart

### ISSUE THREAD

**Issue by dotI0** [PryPurity/WorldBorder#18]
**Describe the bug**:

World Border won't resume fill job after restart, because WorldBorder is loaded before the World will be initialized by Multiverse. (As seen in Line 727 of the following log)

[2020-09-22-1.log](https://github.com/PryPurity/WorldBorder/files/5259173/2020-09-22-1.log)

**Server Version**:
Paper#202-1.16.3

**Plugin Version**:
2.0.9

**Plugins**:
Plugins (54): AdvancedBan*, AreaShop, AsyncWorldEdit, Bank, BestTools, BungeeTabListPlus, ChestCommands, ChestShop, ChestSort, Citizens, ClearLag, CommandNPC*, Commandspy*, Core, CoreProtect, DisableJoinMessage*, dynmap*, EditableSign, EntityTrackerFixer, Essentials, EssentialsChat, EssentialsSpawn, FreeBungeeChat*, HolographicDisplays, IPortal, Jobs, Lands, LWC, Microblocks*, Multiverse-Core, Multiverse-Inventories, Multiverse-Portals, OpenInv, PermissionsEx*, PlaceholderAPI, Plot2Dynmap, PlotSquared, ProtocolLib, QuickBoard*, React*, RemoteToolkitPlugin*, ServerSigns, ServerTutorialPlus*, SignColours*, SimpleBroadcast*, TheNewEconomy, UltimateTimber, Vault, Votifier, VotingPlugin, WelcomeBookRecoded, WorldBorder, WorldEdit, WorldGuard

**Comment by dotI0** [comment]
I fixed it! I've added Multiverse-Core to your plugin.yml as soft depend.
Can you add this to your next build?
[plugin.yml.txt](https://github.com/PryPurity/WorldBorder/files/5261120/plugin.yml.txt)

**Comment by PryPurity** [comment]
Will do!
