### ISSUE TITLE
Error Exception - TIMING_STACK_CORRUPTION

### ISSUE THREAD

**Issue by Rend-Creator** [PryPurity/WorldBorder#2]
I was generating a 20k x 20k map then suddenly this error appeared. I immediately stopped the task to prevent any further corruptions that might occur.

![Capture](https://user-images.githubusercontent.com/61183625/85247479-73cf4b00-b480-11ea-8b4d-b8e31eccb2d3.PNG)

**Comment by Rend-Creator** [comment]
Plugins:
Dynmap
WorldBorder
Protocolib
Vault
Multiverse-Core
Multiverse-Inventory

Server Client:
Paper 1.15.2 Build 365

**Comment by PryPurity** [comment]
Heya, Sorry for the late reply, github apparently didn't alert me to this. I have stated on the spigot page "USE CAUTION WHEN DEALING WITH PAPER. IF IT ERRORS OUT, RESTART IT"

If it continues to cause an error, using spigot to generate the map, then switching to paper after it is complete should fix this. 

The PaperAPI seems to have broken when updating to 1.15, so I can currently re-coding the whole source code itself.

Let me know how this goes! <3

EDIT: Try running the latest version on spigot, I had commented out the code for now.

**Comment by PryPurity** [comment]
Do NOT use version 2.0.4, btw, use version 2.0.3

**Comment by Rend-Creator** [comment]
Yeah I've seen your warning, I hope paper updates their versions to not mess with the plugins. I see that you don't want us to use the 2.0.4? I need that version because you said it supports 1.16 which btw I'm creating a server for 1.16 :D

**Comment by PryPurity** [comment]
Version 2.0.5 should be a fix for 2.0.4 ( First 1.16 release ), I believe that this is now "solved"? ;3

**Comment by PryPurity** [comment]
Closing due to this being solved. <3
