### ISSUE TITLE
random chunks outside border

### ISSUE THREAD

**Issue by ScuroK** [PryPurity/WorldBorder#20]
**Describe the bug**:
random chunks appeared outside the border. trim does not remove them.
**Server Version**:
paper 1.16.3
**Plugin Version**:
2.1.0
**Plugins**:
multiverse core, world border
![Unbenannt](https://user-images.githubusercontent.com/10480144/95003767-d4733580-05e2-11eb-95be-bb732f23e35c.PNG)

**Comment by PryPurity** [comment]
I'll take a closer look at it sooner or later. Bit busy with some other projects atm.
