### ISSUE TITLE
Can't expand World Border

### ISSUE THREAD

**Issue by fmarkulin** [PryPurity/WorldBorder#25]
**Describe the bug**: I've set the border with /wb world set 10000. I now want it to be /wb world set 20000. The console says it changed, but it didnt change  in the game. Bypass also doesnt work. I've tried to clear it, also nothing. I've tried to make it smaller, nothing. I've deleted it completely, nothing. I really don't know what to do anymore, I'm beat...

**Server Version**: Paper 1.16.4

**Plugin Version**: 2.1.0

**Plugins**: EssentialsX, ChatEx, WorldEdit, WorldGuard, LuckPerms, CoreProtect, Vault, AmkMcAuth, BlockLocker, Harbor, SkinsRestorer, WorldBorder

**Comment by fmarkulin** [comment]
Fixed it by using the /worldborder command instead of /wb. Possibly something was overriding it, IDK. Support helped on discord. Many thanks!

**Comment by Caleston** [comment]
> Fixed it by using the /worldborder command instead of /wb. Possibly something was overriding it, IDK. Support helped on discord. Many thanks!

I'm having the same issue, but using /worldborder:wb or /worldborder:wborder is doing nothing, a specific /worldborder command doesnt even seem to exist. I'm unable to clear the border at all.
