### ISSUE TITLE
/wb trim not work

### ISSUE THREAD

**Issue by mabinkitsune** [PryPurity/WorldBorder#27]
**Describe the bug**:
I did `/wb trim`, as well as `/wb trim confirm`, but nothing happened after finishing the process.
![123](https://user-images.githubusercontent.com/78536362/106878832-3f04c100-66fc-11eb-95b2-be78b87b4174.PNG)
(after the process, I made a new render of the web-map)

**Server Version**:
Spigot 1.16.5

**Plugin Version**:
WorldBorder 2.1.0

**Plugins**:
LuckPerms 5.1.93
Dynmap 3.1-beta6
DiscordSRV 1.20.0

**Comment by mabinkitsune** [comment]
Plugin does trim, but not completely

**Comment by 00Hrtz** [comment]
doesn't trim for me at all, not a single block

**Comment by PreciseOXT** [comment]
Hi
I have the same issue on same version, Paper 1.16.5 using WB 2.1.0
Plugin says trim is working and completed, but no chunks are removed and chunks still generate outside of border.

**Comment by 00Hrtz** [comment]
> 
> 
> Hi
> I have the same issue on same version, Paper 1.16.5 using WB 2.1.0
> Plugin says trim is working and completed, but no chunks are removed and chunks still generate outside of border.

I gave up with it myself, no one answered any of my posts on discord so i deleted them all and decided i'd find something else if and when i required.

**Comment by 4o3F** [comment]
Having the same problem
