### ISSUE TITLE
Exception Error: Fill Command

### ISSUE THREAD

**Issue by Rend-Creator** [PryPurity/WorldBorder#3]
**Describe the bug**:
So I have a time to test this because you've mentioned that you cannot test this to your server, here is one of the results I get:

After executing the /wb nether_world fill 20, the server immediately throws an exception on the server console then the filling process is paused. It just stay there on the exception error that was thrown.

**Server Version**:
Spigot 1.16.1

**Plugin Version**:
2.0.4
Yeah you said don't use 2.0.4 but I can't find any download link for 2.0.3.

**Plugins**:

***All Plugins are in its latest versions and all of them are working***
Multiverse Core
Multiverse Inventory
EssentialsX
Luckperms
Vault
WorldEdit
WorldGuard

WorldBorder 1.15+ (The plugin itself)

Here's the photo of the console:
![Capture](https://user-images.githubusercontent.com/61183625/85777673-65b94d00-b754-11ea-8f88-78ee70ee53ca.PNG)

**Comment by PryPurity** [comment]
Yeah, kinda figured it would still be broke, thank you for reporting this! Fixing it now.

**Comment by PryPurity** [comment]
Fixed, and working as of 2.0.5, closing bug.
