### ISSUE TITLE
Border warping player to the bottom of the ocean

### ISSUE THREAD

**Issue by Stechi** [PryPurity/WorldBorder#33]
**Describe the bug**:
Player was outside the border and got teleported to the bottom of the ocean,
instead of on top of it, where there are airblocks.
"safe vertical location" error

**Server Version**:
1.16.5
Paper-483

**Plugin Version**:
2.1.1

**Plugins**:
BBOutline-Reloaded; Betetr Sleeping; CoreProtect; craftbook; Dynmap; Dynmap-Griefprevention; EssentialsX; EssentialX-Protect; FastAsyncWorldedit; GriefPrevention; LuckPerms; MarriageMaster; Multiverse-Core; Multiverse-Inventories; Multiverse-Portals; OpenInv; PluginLibrary; ProtocolLib; Vault; VillageInfo; WorldEditSUI

**Comment by PryPurity** [comment]
Try this version:

[WorldBorder.zip](https://github.com/PryPurity/WorldBorder/files/6331740/WorldBorder.zip)

**Comment by PryPurity** [comment]
Closing due to no response.
