### ISSUE TITLE
Reaching the border with elytras

### ISSUE THREAD

**Issue by ghost** [PryPurity/WorldBorder#34]
Hello,

When we reach the border while using elytras, we are teleported back to the ground.
On the other hand when we reach the border while flying in creative mode, the behaviour is different : We are teleported ~3 blocks back but on the same Y coordinates.
Could it be possible to have the same behaviour in elytras please ?

**Comment by PryPurity** [comment]
It's going to stop a player upon impact anyway, since a player isn't able to go anywhere, they will just fall straight down and die. While it sounds like a good idea on paper, not very good overall.

**Comment by ghost** [comment]
Oh, okay. Why would it stop the player from gliding ?
I'm assuming the plugin is teleporting players a few blocks back when I hit the border. 
As a test, if I'm gliding on elytras and I use a `/minecraft:tp` command to teleport myself elsewhere but still in the air, I will still be gliding.

**Comment by PryPurity** [comment]
Mmmm, I still don't know man, I feel as if an anticheat will just kick a player for that.

**Comment by ghost** [comment]
I will elaborate onto why I think this is important (at least for me, but others can also experience this problem).
I have a world which is like a "Skyblock" world. There are islands floating around but it's mostly void. Players are exploring this world mainly **using elytras**.

The problem is, when they reach the border while using elytras they are teleported in x=0,y=60,z=0 which is inside a block so they die.
I understood that WorldBorder is trying to teleport them on ground. But as there no ground, the plugin is not handling it correctly. In the rare case when a player reaches the border with a floating island beneath him, he is teleported on this island.

Please explain to me the difference for an anticheat between WorldBorder teleporting you back on land (which can be far from where you were gliding) or just ~3 blocks back but still gliding on elytras as you were before.

**Comment by PryPurity** [comment]
Sorry for the late response, Was feeling a bit off, so I re-read what the main question was and the answer is pretty simple. Creative mode allows a Toggle Fly on/off, able to ACTUALLY FLY and stop whenever you want; While elytras is based on you actually not flying and toggling, but gliding. You can't stop in one spot while Gliding with elytras for long periods of time. 

Since you can stay still in the air without moving in creative, ( also you are pretty much invincible, can't take damage ) the plugin counts the air blocks as a "safe spot" due to you not actually going to fall down, and that your FLYING is TOGGLED ON.. 

I hope what I said makes sense, it's kinda rough to understand but that's pretty much the answer I can come up with.

**Comment by ghost** [comment]
No worries for the late response we are not in a hurry.
It seems to me that you don't use elytras often. No you're not gonna fall down instantly. If you chose to be gliding with elytras then AIR is a safe spot to be teleported to because you were already in the air.
Conversely, ground could be an unsafe spot if there are mobs around that you chose to avoid using elytras.

But okay let's say that air is not safe. I think there is still a bug that I tried to explain above : 
When I reach the border using elytras and there is no "safe ground" then the plugin is teleporting me in a wall and I die. It happens in a "Skyblock" world where it's mostly void or in the nether when there is lava below me.

**Comment by PryPurity** [comment]
As I had previously stated beforehand, elytras are not technically "flying", they are "Gliding". Flying being able to toggle on/off, go up/down and stay in one spot in the air, while gliding being (I guess toggleable) a constant movement, going only down.

**Comment by ghost** [comment]
What does this have to do with my last message ? Do you want me to open another issue now that we agreed that teleporting the player to the ground is a good behaviour ? In this new issue I will describe situations when the teleportation is not done correctly.

**Comment by PryPurity** [comment]
If it's a bug report, then this should have been made as a bug report to begin with. As far as I'm aware, if there is no safe spot, it will teleport the player to the world's spawn. I believe it counts 0/(random height)/0 as the default coords, not really checked too much into that part of the code. As I have stated before, I am simply maintaining this project until further notice. Developers are free to push changes that could/would fix an issue and I can release a version with it.

**Comment by ghost** [comment]
> If it's a bug report, then this should have been made as a bug report to begin with.

Before reporting the bug I wanted to discuss why is the player teleported to the ground while on elytras. Because if you had agreed that this was not a good behaviour and changed it, there would have been no bug to report.

> As far as I'm aware, if there is no safe spot, it will teleport the player to the world's spawn.

You might be right, this position could be the spawn of the world. More precisely the spawn of the map if I play on this map in singleplayer for example.
But as I redefined the spawn using Multiverse a long time ago, I had no idea what this coordinate was.
