### ISSUE TITLE
Server no respond and then crash while fill the world with no limit rate

### ISSUE THREAD

**Issue by RuofengX** [PryPurity/WorldBorder#37]
With unlimited rate like `wb world fill 1000`, my server crash

### System info:
- Latest release WorldBorder 2.1.2
- 1.16.5 using Paper-777.jar
- Java16 using -Xms4G -Xmx5G
- Ubuntu 
- 2 Core AMD EPYC, 8G RAM
- Run a website with MySQL Nginx PHP7.4-fpm, but several access when crash

**Here is the full [log](https://paste.ee/p/4MGLx)**

I know that run a fill work without limit is not "stable", but I want know what's wrong when server crashing. Does it caused by the high load of CPU?

**Comment by PryPurity** [comment]
Looks like a high load of CPU. Worldborder requires a bit of CPU power to work.

Will look more into this.

**Comment by M4T14SG4M3R** [comment]
It also crashes when the fill is 1 chunk and 1 pad per attempt with a 10k limit world on 30GB ram, only filled 0.1% and all ram was used

**Comment by PryPurity** [comment]
> 
> 
> It also crashes when the fill is 1 chunk and 1 pad per attempt with a 10k limit world on 30GB ram, only filled 0.1% and all ram was used

This is literally no help at all.
