### ISSUE TITLE
Worldborder trim doesnt trim chunks

### ISSUE THREAD

**Issue by JHarris12345** [PryPurity/WorldBorder#38]
I am on the latest versions and MC 1.16.5. There is an issue where trimming the world doesnt trim any chunks, it only trims region files. So it trims from the border of the region file and not the worldborder. I.e If I set my border to 100 and try to trim, it wont start trimming until 512 blocks out

**Comment by PryPurity** [comment]
Have you tried to delete all your dynmap files and re-render?

**Comment by JHarris12345** [comment]
Dynmap is not installed, nor is there any dynmap folder

**Comment by PryPurity** [comment]
Why would you want to trim at 100 to begin with? Might as well just make a void world and paste in that area?

**Comment by JHarris12345** [comment]
I want to trim at 257 and that is to reset faction maps weekly. Doing it via pasting a schematic will not work as that will require a new shcmeatic to be made every time you change the contents of that area.

it works fine on 1.8, it would be really handy to have it working on 1.16+ or at least figure out what causes it to not work

**Comment by PryPurity** [comment]
Mmmm, I'll check it out whenever I have free-time. If you have any logs that I can take a look at, that would be great as well.

**Comment by JHarris12345** [comment]
Here is a startup log https://pastebin.com/tfXEqkd1

**Comment by PryPurity** [comment]
I can't tell anything by the startup logs at all. Can you send me a spark log with the plugin trimming from the command?
