### ISSUE TITLE
Setting the WorldBorder message to "" bugs out the config

### ISSUE THREAD

**Issue by DrkMatr1984** [PryPurity/WorldBorder#39]
I'd like a way to just set wrap and avoid using the worldborder message altogether. However, setting the message to "" from inside the plugin using the /wb setmsg command works only until the next restart, and then the config is misparsed and replaced by the default config.

**Comment by DrkMatr1984** [comment]
Looks like this would be the culprit
https://github.com/PryPurity/WorldBorder/blob/87ab7acca605fee6d43a14c288419021776a6789/src/main/java/com/wimbli/WorldBorder/Config.java#L558-L565
Anyway to make sure that the worldborder is correct other than checking for the worldborder message? That seems kind of dumb that I can't set it to ""

**Comment by PryPurity** [comment]
"/wb list - show full border information for all worlds.

Permission: worldborder.list"

https://www.spigotmc.org/threads/worldborder.339635/#post-3162179

**Comment by DrkMatr1984** [comment]
I think you misunderstood me. I would like to disable the message that says "you have reached the end of the world", but currently there is no way to disable that message getting sent when someone reaches the worldborder.
Doing /wb setmsg "" to set it as blank works only until a server restart, because of the line of code I highlighted, which uses the worldborder message setting to detect if the config is fucked up or not. If the worldborder message is blank, it resets the entire config on next reboot.

**Comment by DrkMatr1984** [comment]
#40 Fixes this

**Comment by PryPurity** [comment]
Closing issue to do recent Commit fixing, Thank you.
