### ISSUE TITLE
Add support for Minecraft version 1.18?

### ISSUE THREAD

**Issue by davidjpfeiffer** [PryPurity/WorldBorder#41]
Is there an ETA on when support for 1.18 will be added? I tried asking on Discord but your Discord server sucks.

**Comment by davidjpfeiffer** [comment]
I am able to use the current version of this plugin on my 1.18 Paper server without any obvious issues, so maybe it does not need to be updated. But official support for 1.18 would be appreciated :)

**Comment by PryPurity** [comment]
Sorry for the late reply, holidays and new house has finally settled down. Plugin should still be working on 1.18

**Comment by davidjpfeiffer** [comment]
No worries, thank you for the confirmation!
