### ISSUE TITLE
1.18.1 Server run our of member

### ISSUE THREAD

**Issue by CloudeLecaw** [PryPurity/WorldBorder#42]
Our Server has 22gb ram.
We tried to fill a world with a bother of radius 5000
The ram increases instantly up the ram is filled completly and the server crashes because he is our of Memory.
Is there a chance to limit the amout of Ram used for trimming?
If not it needs to be fixed.

the file said ther where still 7 gb left but this is not the fact. the 7gb more ram are used for a secound miniserver bebcause the server source is splitted into two parts..

PaperMC 1.18.1
WorldBorder 1.15+ 2.1.4

![Snag_2c11548](https://user-images.githubusercontent.com/12080017/146623748-5e0f354e-d3b0-4c8a-bc4c-50eb4604b85b.png)

Update:  looks like the OoM just appears when it starts the 3D-Rendering...

**Comment by PryPurity** [comment]
Will look into this further.
