### ISSUE TITLE
World does not fill

### ISSUE THREAD

**Issue by oranges13** [PryPurity/WorldBorder#43]
We have been using Worldborder for a while, but we recently have encountered an issue with filling where the status says that the world has been filled but when players actually begin to move around the world, the server behaves like the chunks are not generated and our TPS drops significantly.

We are using the most recent version on 1.17.1. We also experienced the issue on 1.16 with the prior version as well.

**Comment by PryPurity** [comment]
mmm, I will look into this further, but highly recommend moving up to the latest minecraft version.

**Comment by oranges13** [comment]
We are a modded server and not all of our required mods have upgraded to 1.18 yet. We are at the highest version we can be at given our current feature set.

**Comment by PryPurity** [comment]
Ahh, okay, do you have any world generation changing mods that do not spawn in vanilla blocks? That might be an issue, or it's the mods that are making the time take forever to load. Can you grab a /timings paste and post it in here for me to look at please? Before and after everyone teleports.

**Comment by oranges13** [comment]
No non-vanilla mods (like FTB or anything like that). We have stopped using WorldBorder for the time being because our system is live and the lack of pre-filling was killing our server.

What do you mean before / after teleporting?

**Comment by PryPurity** [comment]
Do a timings report before anyone teleports, and another timings report after players teleport.

**Comment by PryPurity** [comment]
Closing due to no reports.
