### ISSUE TITLE
Config changes are reset on server restart

### ISSUE THREAD

**Issue by davidjpfeiffer** [PryPurity/WorldBorder#44]
I am trying to make changes to the `WorldBorder/config.yml` file but all of the changes that I make are reset after restarting the server. in other words, there is no way for me to actually change any of the config values.

Let me know if there is any additional information I can provide. It would be awesome to get a fix for this ASAP!

**Comment by Peskdt** [comment]
This problem happens to me too. Purpur 1.17.1 java 17

**Comment by PryPurity** [comment]
Would it be possible to know what all you are trying to change in the config? It shouldn't be making it reset unless you are tabbing and it's ruining the layout of the config.

**Comment by davidjpfeiffer** [comment]
@PryPurity I think it happens regardless of what change I make, but for example, it happens when I change `dynmap-border-enabled` from `true` to `false`

**Comment by Peskdt** [comment]
I change the x-z radius from a world, but it changes to 9999 ever.

**Comment by PryPurity** [comment]
> @PryPurity I think it happens regardless of what change I make, but for example, it happens when I change `dynmap-border-enabled` from `true` to `false`

Interesting. I'll take a look at it this weekend.



> I change the x-z radius from a world, but it changes to 9999 ever.

I think you are still using an old version of the plugin. This has been fixed for quite a while.

**Comment by PryPurity** [comment]
I guess the new version should fix the config changing? And no response from Peskdt, so going to go with, using the old WorldBorder

**Comment by davidjpfeiffer** [comment]
@PryPurity this fixed my issue! Thank you for the update!

**Comment by PryPurity** [comment]
No problem!

**Comment by Peskdt** [comment]
I can't try it, because when the limit changed to 9999 it started to generate a vanilla world in my earth server xD, so, I'm still using the world border in the lobby world, but I'm afraid to use it in my 80gb world.

**Comment by PryPurity** [comment]
> I can't try it, because when the limit changed to 9999 it started to generate a vanilla world in my earth server xD, so, I'm still using the world border in the lobby world, but I'm afraid to use it in my 80gb world.

What Version of the plugin are you running?
