### ISSUE TITLE
Memory Leak & Gradual Speed Reduction

### ISSUE THREAD

**Issue by Goonhaven** [PryPurity/WorldBorder#5]
**Describe the bug:** Memory used increases over time, despite frequent (30 - 60s) save intervals; chunks loaded start high, as expected for pre-loaded chunks, but then slow to a snail pace of 0 - 10 chunks per second despite being on 50 chunks / sec setting. Server crashes when stopped.

Memory leak log: https://pastebin.com/gUKi1LRJ
Crash log: https://pastebin.com/jezvyPpB

**Server Version:** Spigot 1.16.1 (CraftBukkit version git-Spigot-ad703da-d77f4d9).
The server is started with no extra parameters apart from RAM use: 'java -jar -Xms1G -Xmx10G spigot-1.6.1.jar'

**Plugin Version:** 2.0.5

**Plugins:** EssentialsX, EssentialsXSpawn, Multichat, PermissionsEx, IRC Plugin, Vault, WorldBorder.

**Comment by PryPurity** [comment]
Heya, do you mind sending me your server specs as well? I don't have this happening on my personal server.

**Comment by cobrex1** [comment]
I have had very similar issues, testing on my local machine - Xms12G -Xmx12G -XX:+UseConcMarkSweepGC -jar paperclip-27.jar
1.16.1

I have used /wb fill 20 100 true as the start command. This has proved more reliable, but got very similar crash reports above.

Crash Log: https://hastebin.com/egazupijih.md

I am sure it is due to a memory issue. I pause the generation and restart when the memory has cleared down. Not an ideal solution as needs to be watched constantly.

**Plugin Version:** 2.0.5

**Other Plugins:** EssentialsX, EssentialsXSpawn, Multiverse, Sparks, Vault, worldedit, worldguard, worldguardextraflags

**Comment by Goonhaven** [comment]
> Heya, do you mind sending me your server specs as well? I don't have this happening on my personal server.

Hi, no worries:

Linux (CentOS)
32GB RAM,
Intel(R) Xeon(R) CPU E3-1245 V2 @ 3.40GHz
1.8TB HDD

There's a further development - I can't actually finish the fill task as it always crashes before reaching 100%. I've been doing the same as cobrex1 above - stopping and restarting when it reaches low memory. The note that spigot leaves before a crash is if it says 'world saving' before the crash then the system has been severely overtaxed, but as far as I can tell, at least 12GB RAM is available before starting and the HDD was recently formatted so there shouldn't be corruption. The CPU isn't the most powerful in the world, but that shouldn't cause a crash, should it?

I've tried /wb world fill 50, /wb world fill 1000, /wb world fill 30, and am now using the following parameters:
'java -jar -server -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSIncrementalPacing -XX:ParallelGCThreads=7 -XX:+AggressiveOpts -Xms1G -Xmx8G -jar spigot-1.16.1.jar'

We don't really want to switch to paperclip, but would be willing to try just to generate the rest of the world, though it seems cobrex1 experienced the same problem with paperclip.

**Comment by PryPurity** [comment]
> I have had very similar issues, testing on my local machine - Xms12G -Xmx12G -XX:+UseConcMarkSweepGC -jar paperclip-27.jar
> 1.16.1
> 
> I have used /wb fill 20 100 true as the start command. This has proved more reliable, but got very similar crash reports above.
> 
> Crash Log: https://hastebin.com/egazupijih.md
> 
> I am sure it is due to a memory issue. I pause the generation and restart when the memory has cleared down. Not an ideal solution as needs to be watched constantly.
> 
> **Plugin Version:** 2.0.5
> 
> **Other Plugins:** EssentialsX, EssentialsXSpawn, Multiverse, Sparks, Vault, worldedit, worldguard, worldguardextraflags



> > Heya, do you mind sending me your server specs as well? I don't have this happening on my personal server.
> 
> Hi, no worries:
> 
> Linux (CentOS)
> 32GB RAM,
> Intel(R) Xeon(R) CPU E3-1245 V2 @ 3.40GHz
> 1.8TB HDD
> 
> There's a further development - I can't actually finish the fill task as it always crashes before reaching 100%. I've been doing the same as cobrex1 above - stopping and restarting when it reaches low memory. The note that spigot leaves before a crash is if it says 'world saving' before the crash then the system has been severely overtaxed, but as far as I can tell, at least 12GB RAM is available before starting and the HDD was recently formatted so there shouldn't be corruption. The CPU isn't the most powerful in the world, but that shouldn't cause a crash, should it?
> 
> I've tried /wb world fill 50, /wb world fill 1000, /wb world fill 30, and am now using the following parameters:
> 'java -jar -server -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSIncrementalPacing -XX:ParallelGCThreads=7 -XX:+AggressiveOpts -Xms1G -Xmx8G -jar spigot-1.16.1.jar'
> 
> We don't really want to switch to paperclip, but would be willing to try just to generate the rest of the world, though it seems cobrex1 experienced the same problem with paperclip.

Thank you both for the reports! I will take a further investigation into what all is going on here, My current plan is to at least get the re-code done by the end of july or august, which should fix almost every single problem that the plugin currently has of right now.

**Comment by PryPurity** [comment]
Pushed a new release: 2.0.6

https://www.spigotmc.org/resources/worldborder-1-15.80466/

let's do a test run with that on Paper Version - 32
