### ISSUE TITLE
World loading issues 

### ISSUE THREAD

**Issue by arturek1666** [PryPurity/WorldBorder#6]
**Describe the bug**:
The bug is simple instead of ignoring already loaded chunks it dosn't ignore it and just loads them again. I had world loaded 88% and it started from 0% and loads just like would an fresh world, Yes I did do /wb world fill 1000 208 false, to make sure it skips the loaded chunks but it dosn't 
**Server Version**:
1.16.1
**Plugin Version**:
2.0.7
**Plugins**:
(Not needed for this issue)

**Comment by PryPurity** [comment]
Alrighty, thank you for the report! I will check into this as well! :) 👍

**Comment by kero93x** [comment]
Had the same issue it was at 5% and it crashed and is not skipping the chunks already loaded

**Comment by vaniron** [comment]
Building new jar from https://github.com/Puremin0rez/WorldBorder fixed this. Just so you know where to find it.

**Comment by arturek1666** [comment]
The link you have given is a worldborder created by other user. Not the author of this thread xD

**Comment by vaniron** [comment]
In fact both of these versions are forks from same original source. So its easy to push PRs from given link. Dont try to look clever when you dont know what you talk about :)

**Comment by arturek1666** [comment]
Even if the code is from the previous author the rest might be different etc. They both can have different ways of coding etc. xD

**Comment by vaniron** [comment]
Whatever, keep on hating. Doing good job.

**Comment by arturek1666** [comment]
It's not a hate I just think that even if this author or other is using original resource and modifies it after that they both are different as it's different developer different ideas. So advertising other person worldborder is not really nice that's all I have to say. So yeah :) if other worldborder works for you that's fine. But I want to stay and wait for this developer to finish it :) who knows in the end it might be better then other :), as this author is planing on doing rewrite :) so a lot of stuff in code will change :)

**Comment by vaniron** [comment]
Ok, lets educate.
Comparing the fix https://github.com/Puremin0rez/WorldBorder/commit/c1d99e560c227b2b5e3a5fb2f0d410159ff3d810 with current version in THIS repo https://github.com/Brettflan/WorldBorder/blob/master/src/main/java/com/wimbli/WorldBorder/Config.java proves you are WRONG.

As i said stop commenting something you HAVE NO IDEA ABOUT. Those codes are fully compatible and its your own opinion and problem if you think sharing fix within community is bad. You are not competent to make such statements, its fully in hands of repo author what he wanna or doesnt wanna use. If you think i posted the fix to advertize i did not and again it is your misunderstanding.

**Comment by arturek1666** [comment]
Well I sometimes comment without thinking but that just me, anyway it's true that I might have over reacted a bit my bad.

**Comment by PryPurity** [comment]
This should be fixed in 2.0.9. Closing issue.
