### ISSUE TITLE
Chunks still generate on edge of world border

### ISSUE THREAD

**Issue by OmegaShaman** [PryPurity/WorldBorder#7]
So every time i go to the world border after a trim, new chunks still generate and I have no idea why they do. I ran a trim a few times with different settings and they still generate. I use Spigot, Paper and Akarin and an Earth map, and I also use the WorldBorder plugin along with Dynmap, Multiverse-Core, etc.

Any way I can fix this?

**Comment by PryPurity** [comment]
This is intentional. This is so players do not generate new chunks outside of the worldborder region.
