### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by scalda** [PryPurity/WorldBorder#9]
Hi is there a chance to have an option to turn off the bypass to allow anyone to go past the border.

We currently use an old modified version that achieves this for us but we would like to update to a version that's actually made against 1.16. so I am asking here if this can be done within your update

regards

Scalda

**Comment by PryPurity** [comment]
Did not know the current version doesn't allow you to bypass the border, interseting. I'll take a look into it!

**Comment by dotI0** [comment]
You can bypass the border with "wb bypass <player> [on|off] - let player go beyond border." i think.
